#pragma once

// Adapter to map taipo positions to a set of key positions from urob's zmk-helpers.
// Allows the disabling of either hand for single-handed keyboards

#ifdef TAIPO_ONLY_RIGHT_HAND
#define TAIPO_POS_LT1 TAIPO_UNUSED_POS
#define TAIPO_POS_LT2 TAIPO_UNUSED_POS
#define TAIPO_POS_LT3 TAIPO_UNUSED_POS
#define TAIPO_POS_LT4 TAIPO_UNUSED_POS
#define TAIPO_POS_LM1 TAIPO_UNUSED_POS
#define TAIPO_POS_LM2 TAIPO_UNUSED_POS
#define TAIPO_POS_LM3 TAIPO_UNUSED_POS
#define TAIPO_POS_LM4 TAIPO_UNUSED_POS
#define TAIPO_POS_LH0 TAIPO_UNUSED_POS
#define TAIPO_POS_LH1 TAIPO_UNUSED_POS
#else
#define TAIPO_POS_LT1 LT1
#define TAIPO_POS_LT2 LT2
#define TAIPO_POS_LT3 LT3
#define TAIPO_POS_LT4 LT4
#define TAIPO_POS_LM1 LM1
#define TAIPO_POS_LM2 LM2
#define TAIPO_POS_LM3 LM3
#define TAIPO_POS_LM4 LM4
#define TAIPO_POS_LH0 LH0
#define TAIPO_POS_LH1 LH1
#endif

#ifdef TAIPO_ONLY_LEFT_HAND
#define TAIPO_POS_RT1 TAIPO_UNUSED_POS
#define TAIPO_POS_RT2 TAIPO_UNUSED_POS
#define TAIPO_POS_RT3 TAIPO_UNUSED_POS
#define TAIPO_POS_RT4 TAIPO_UNUSED_POS
#define TAIPO_POS_RM1 TAIPO_UNUSED_POS
#define TAIPO_POS_RM2 TAIPO_UNUSED_POS
#define TAIPO_POS_RM3 TAIPO_UNUSED_POS
#define TAIPO_POS_RM4 TAIPO_UNUSED_POS
#define TAIPO_POS_RH0 TAIPO_UNUSED_POS
#define TAIPO_POS_RH1 TAIPO_UNUSED_POS
#else
#define TAIPO_POS_RT1 RT1
#define TAIPO_POS_RT2 RT2
#define TAIPO_POS_RT3 RT3
#define TAIPO_POS_RT4 RT4
#define TAIPO_POS_RM1 RM1
#define TAIPO_POS_RM2 RM2
#define TAIPO_POS_RM3 RM3
#define TAIPO_POS_RM4 RM4
#define TAIPO_POS_RH0 RH0
#define TAIPO_POS_RH1 RH1
#endif
