#pragma once

// Adapter to map taipo positions to a set of key positions from urob's zmk-helpers.
// Allows the disabling of either hand for single-handed keyboards

#ifndef TAIPO_ONLY_RIGHT_HAND
#define TAIPO_POS_L_T1 TAIPO_UNUSED_POS
#define TAIPO_POS_L_T2 TAIPO_UNUSED_POS
#define TAIPO_POS_L_T3 TAIPO_UNUSED_POS
#define TAIPO_POS_L_T4 TAIPO_UNUSED_POS
#define TAIPO_POS_L_M1 TAIPO_UNUSED_POS
#define TAIPO_POS_L_M2 TAIPO_UNUSED_POS
#define TAIPO_POS_L_M3 TAIPO_UNUSED_POS
#define TAIPO_POS_L_M4 TAIPO_UNUSED_POS
#define TAIPO_POS_L_H0 TAIPO_UNUSED_POS
#define TAIPO_POS_L_H1 TAIPO_UNUSED_POS
#else
#define TAIPO_POS_L_T1 LT1
#define TAIPO_POS_L_T2 LT2
#define TAIPO_POS_L_T3 LT3
#define TAIPO_POS_L_T4 LT4
#define TAIPO_POS_L_M1 LM1
#define TAIPO_POS_L_M2 LM2
#define TAIPO_POS_L_M3 LM3
#define TAIPO_POS_L_M4 LM4
#define TAIPO_POS_L_H0 LH0
#define TAIPO_POS_L_H1 LH1
#endif

#ifndef TAIPO_ONLY_LEFT_HAND
#define TAIPO_POS_R_T1 TAIPO_UNUSED_POS
#define TAIPO_POS_R_T2 TAIPO_UNUSED_POS
#define TAIPO_POS_R_T3 TAIPO_UNUSED_POS
#define TAIPO_POS_R_T4 TAIPO_UNUSED_POS
#define TAIPO_POS_R_M1 TAIPO_UNUSED_POS
#define TAIPO_POS_R_M2 TAIPO_UNUSED_POS
#define TAIPO_POS_R_M3 TAIPO_UNUSED_POS
#define TAIPO_POS_R_M4 TAIPO_UNUSED_POS
#define TAIPO_POS_R_H0 TAIPO_UNUSED_POS
#define TAIPO_POS_R_H1 TAIPO_UNUSED_POS
#else
#define TAIPO_POS_R_T1 RT1
#define TAIPO_POS_R_T2 RT2
#define TAIPO_POS_R_T3 RT3
#define TAIPO_POS_R_T4 RT4
#define TAIPO_POS_R_M1 RM1
#define TAIPO_POS_R_M2 RM2
#define TAIPO_POS_R_M3 RM3
#define TAIPO_POS_R_M4 RM4
#define TAIPO_POS_R_H0 RH0
#define TAIPO_POS_R_H1 RH1
#endif
